2>build_SPIRV_errors.log cls 
mkdir WickedEngine\shaders 
cd WickedEngine\shaders 
mkdir spirv
cd .. 
..\shadercompilers\dxc bloomcombineCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/bloomcombineCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc bloomseparateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/bloomseparateCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc downsample4xCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/downsample4xCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_bilateral_float1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_bilateral_float1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_bilateral_float3CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_bilateral_float3CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_bilateral_unorm4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_bilateral_unorm4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_bilateral_wide_float1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_bilateral_wide_float1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_bilateral_wide_float3CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_bilateral_wide_float3CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_bilateral_wide_float4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_bilateral_wide_float4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_bilateral_wide_unorm1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_bilateral_wide_unorm1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_bilateral_wide_unorm4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_bilateral_wide_unorm4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_gaussian_float1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_gaussian_float1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_gaussian_float3CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_gaussian_float3CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_gaussian_unorm1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_gaussian_unorm1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_gaussian_unorm4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_gaussian_unorm4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_gaussian_wide_float1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_gaussian_wide_float1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_gaussian_wide_float3CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_gaussian_wide_float3CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_gaussian_wide_float4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_gaussian_wide_float4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_gaussian_wide_unorm1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_gaussian_wide_unorm1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_gaussian_wide_unorm4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_gaussian_wide_unorm4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc captureImpostorPS_albedo.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/captureImpostorPS_albedo.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc captureImpostorPS_normal.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/captureImpostorPS_normal.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc captureImpostorPS_surface.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/captureImpostorPS_surface.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc chromatic_aberrationCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/chromatic_aberrationCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc circlePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/circlePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc copytexture2D_float4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/copytexture2D_float4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc copytexture2D_float4_borderexpandCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/copytexture2D_float4_borderexpandCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc copytexture2D_unorm4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/copytexture2D_unorm4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc copytexture2D_unorm4_borderexpandCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/copytexture2D_unorm4_borderexpandCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cubeMapPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cubeMapPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cubeShadowVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cubeShadowVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cubeShadowVS_alphatest.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cubeShadowVS_alphatest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc cubeVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/cubeVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc decalPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/decalPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc decalVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/decalVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc deferredPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/deferredPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc depthoffield_mainCS_cheap.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/depthoffield_mainCS_cheap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc depthoffield_mainCS_earlyexit.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/depthoffield_mainCS_earlyexit.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc depthoffield_kickjobsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/depthoffield_kickjobsCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc depthoffield_mainCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/depthoffield_mainCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc depthoffield_neighborhoodMaxCOCCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/depthoffield_neighborhoodMaxCOCCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc depthoffield_postfilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/depthoffield_postfilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc depthoffield_prepassCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/depthoffield_prepassCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc depthoffield_prepassCS_earlyexit.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/depthoffield_prepassCS_earlyexit.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc depthoffield_tileMaxCOC_horizontalCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/depthoffield_tileMaxCOC_horizontalCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc depthoffield_tileMaxCOC_verticalCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/depthoffield_tileMaxCOC_verticalCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc depthoffield_upsampleCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/depthoffield_upsampleCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc dirLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/dirLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc dirLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/dirLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc discLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/discLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc downsampleDepthBuffer4xPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/downsampleDepthBuffer4xPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticlePS_soft_distortion.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticlePS_soft_distortion.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticlePS_soft_lighting.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticlePS_soft_lighting.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_emitCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_emitCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_emitCS_FROMMESH.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_emitCS_FROMMESH.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_emitCS_volume.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_emitCS_volume.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_finishUpdateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_finishUpdateCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_sphpartitionoffsetsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_sphpartitionoffsetsCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_sphpartitionoffsetsresetCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_sphpartitionoffsetsresetCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMapPS_terrain.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMapPS_terrain.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc filterEnvMapCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/filterEnvMapCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain2D_float4_BicubicCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain2D_float4_BicubicCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain2D_unorm4_BicubicCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain2D_unorm4_BicubicCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain2D_unorm4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain2D_unorm4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain3D_unorm4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain3D_unorm4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChainCubeArray_float4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChainCubeArray_float4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChainCubeArray_unorm4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChainCubeArray_unorm4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChainCube_float4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChainCube_float4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChainCube_unorm4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChainCube_unorm4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc gpusortlib_kickoffSortCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/gpusortlib_kickoffSortCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_kickoffUpdateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_kickoffUpdateCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_sphdensityCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_sphdensityCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_sphforceCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_sphforceCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_simulateCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS_DEPTHCOLLISIONS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_simulateCS_DEPTHCOLLISIONS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS_SORTING.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_simulateCS_SORTING.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS_SORTING_DEPTHCOLLISIONS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_simulateCS_SORTING_DEPTHCOLLISIONS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc gpusortlib_sortCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/gpusortlib_sortCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc gpusortlib_sortInnerCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/gpusortlib_sortInnerCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc gpusortlib_sortStepCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/gpusortlib_sortStepCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticle_sphpartitionCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticle_sphpartitionCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc environmentalLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/environmentalLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMapPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMapPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMapVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMapVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMap_skyPS_dynamic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMap_skyPS_dynamic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMap_skyPS_static.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMap_skyPS_static.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc envMap_skyVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/envMap_skyVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc fft_512x512_c2c_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/fft_512x512_c2c_CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc fft_512x512_c2c_v2_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/fft_512x512_c2c_v2_CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc fontPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/fontPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc fontVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/fontVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc forceFieldVisualizerPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/forceFieldVisualizerPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc forceFieldPlaneVisualizerVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/forceFieldPlaneVisualizerVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc forceFieldPointVisualizerVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/forceFieldPointVisualizerVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc fxaaCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/fxaaCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain2D_float4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain2D_float4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc generateMIPChain3D_float4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/generateMIPChain3D_float4_SimpleFilterCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticlePS_forward_transparent.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticlePS_forward_transparent.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticlePS_simplest.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticlePS_simplest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticlePS_tiledforward_transparent.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticlePS_tiledforward_transparent.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticle_simulateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticle_simulateCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hbaoCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hbaoCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_backgroundblur.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_backgroundblur.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_backgroundblur_bicubic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_backgroundblur_bicubic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_backgroundblur_masked.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_backgroundblur_masked.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_backgroundblur_masked_bicubic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_backgroundblur_masked_bicubic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_bicubic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_bicubic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_masked_bicubic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_masked_bicubic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_separatenormalmap_bicubic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_separatenormalmap_bicubic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorPS_alphatestonly.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorPS_alphatestonly.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorPS_deferred.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorPS_deferred.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorPS_forward.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorPS_forward.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorPS_simple.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorPS_simple.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorPS_tiledforward.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorPS_tiledforward.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorPS_wire.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorPS_wire.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc impostorVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/impostorVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc motionblurCS_cheap.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/motionblurCS_cheap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc motionblurCS_earlyexit.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/motionblurCS_earlyexit.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc motionblur_kickjobsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/motionblur_kickjobsCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc motionblur_neighborhoodMaxVelocityCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/motionblur_neighborhoodMaxVelocityCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc motionblur_tileMaxVelocity_horizontalCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/motionblur_tileMaxVelocity_horizontalCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc motionblur_tileMaxVelocity_verticalCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/motionblur_tileMaxVelocity_verticalCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc msaoCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/msaoCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc msao_blurupsampleCS_blendout.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/msao_blurupsampleCS_blendout.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc msao_blurupsampleCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/msao_blurupsampleCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc msao_blurupsampleCS_premin_blendout.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/msao_blurupsampleCS_premin_blendout.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc msao_blurupsampleCS_premin.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/msao_blurupsampleCS_premin.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc msao_interleaveCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/msao_interleaveCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc msao_preparedepthbuffers1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/msao_preparedepthbuffers1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc msao_preparedepthbuffers2CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/msao_preparedepthbuffers2CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred_normalmap_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred_normalmap_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred_terrain.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred_terrain.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_terrain.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_terrain.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_hologram.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_hologram.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_paintradius.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_paintradius.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_terrain.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_terrain.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_voxelizer_terrain.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_voxelizer_terrain.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc oceanSurfacePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/oceanSurfacePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc oceanSurfaceVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/oceanSurfaceVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticleVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticleVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_gaussian_float4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_gaussian_float4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_separatenormalmap.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_separatenormalmap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imagePS_masked.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imagePS_masked.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc imageVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/imageVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lensFlareGS.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lensFlareGS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lensFlarePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lensFlarePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lensFlareVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lensFlareVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_ADVANCED.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_ADVANCED.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_ADVANCED_DEBUG.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_ADVANCED_DEBUG.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_DEBUG.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_DEBUG.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_DEFERRED.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED_ADVANCED.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_DEFERRED_ADVANCED.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED_ADVANCED_DEBUG.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_DEFERRED_ADVANCED_DEBUG.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED_DEBUG.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightCullingCS_DEFERRED_DEBUG.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightShaftsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightShaftsCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lineardepthCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lineardepthCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc paint_textureCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/paint_textureCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vertexcolorPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vertexcolorPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vertexcolorVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vertexcolorVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc luminancePass1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/luminancePass1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc luminancePass2CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/luminancePass2CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc motionblurCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/motionblurCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectDS.hlsl -T ds_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_DS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectDS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectGS_voxelizer.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectGS_voxelizer.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectHS.hlsl -T hs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_HS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectHS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_alphatestonly.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_alphatestonly.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_debug.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_debug.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_blackout.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_blackout.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred_normalmap.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred_normalmap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred_normalmap_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred_normalmap_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_deferred_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_deferred_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_normalmap.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_normalmap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_normalmap_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_normalmap_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_normalmap_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_normalmap_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_transparent.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_normalmap_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_transparent_normalmap_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_normalmap_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_transparent_normalmap_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_transparent_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_transparent_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_simplest.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_simplest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_textureonly.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_textureonly.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_normalmap.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_transparent_normalmap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_normalmap.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_normalmap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_normalmap_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_normalmap_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_normalmap_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_normalmap_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_transparent.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_normalmap.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_transparent_normalmap.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_normalmap_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_transparent_normalmap_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_normalmap_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_transparent_normalmap_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_planarreflection.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_transparent_planarreflection.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_pom.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_transparent_pom.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_water.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_tiledforward_water.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_voxelizer.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_voxelizer.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_common_tessellation.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_common_tessellation.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_common.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_common.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_debug.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_debug.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_positionstream.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_positionstream.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_simple.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_simple.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_simple_tessellation.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_simple_tessellation.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectVS_voxelizer.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectVS_voxelizer.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc oceanSimulatorCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/oceanSimulatorCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc oceanSurfaceSimplePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/oceanSurfaceSimplePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc oceanUpdateDisplacementMapCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/oceanUpdateDisplacementMapCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc oceanUpdateGradientFoldingCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/oceanUpdateGradientFoldingCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc outlinePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/outlinePS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc pointLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/pointLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc pointLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/pointLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticlePS_soft.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticlePS_soft.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticlePS_simplest.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticlePS_simplest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc emittedparticleVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/emittedparticleVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticlePS_alphatestonly.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticlePS_alphatestonly.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticlePS_deferred.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticlePS_deferred.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticlePS_forward.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticlePS_forward.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc hairparticlePS_tiledforward.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/hairparticlePS_tiledforward.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc bvh_propagateaabbCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/bvh_propagateaabbCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc bvh_hierarchyCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/bvh_hierarchyCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc bvh_primitivesCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/bvh_primitivesCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_debugbvhPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_debugbvhPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_kickjobsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_kickjobsCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_screenVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_screenVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_shadeCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_shadeCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_tilesortCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_tilesortCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc rectangleLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/rectangleLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc renderlightmapPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/renderlightmapPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc renderlightmapVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/renderlightmapVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc resolveMSAADepthStencilCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/resolveMSAADepthStencilCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc screenPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/screenPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc screenPS_bicubic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/screenPS_bicubic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc screenVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/screenVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc shadowPS_alphatest.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/shadowPS_alphatest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc shadowPS_transparent.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/shadowPS_transparent.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc shadowPS_water.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/shadowPS_water.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc shadowVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/shadowVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc shadowVS_alphatest.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/shadowVS_alphatest.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc shadowVS_transparent.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/shadowVS_transparent.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc sharpenCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/sharpenCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc skinningCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/skinningCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc skinningCS_LDS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/skinningCS_LDS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc skyPS_static.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/skyPS_static.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc skyPS_dynamic.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/skyPS_dynamic.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc skyVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/skyVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc sphereLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/sphereLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc sphereVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/sphereVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc spotLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/spotLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc spotLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/spotLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc ssaoCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/ssaoCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc ssr_medianCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/ssr_medianCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc ssr_raytraceCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/ssr_raytraceCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc sssPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/sssPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc ssr_resolveCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/ssr_resolveCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc ssr_temporalCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/ssr_temporalCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc sunPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/sunPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc temporalaaCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/temporalaaCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc tileFrustumsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/tileFrustumsCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc tonemapCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/tonemapCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_launchCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_launchCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc raytrace_closesthitCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/raytrace_closesthitCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc trailPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/trailPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc trailVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/trailVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc tubeLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/tubeLightPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_bilateral_float4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_bilateral_float4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc blur_bilateral_unorm1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/blur_bilateral_unorm1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc upsample_bilateralPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/upsample_bilateralPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc upsample_bilateral_float1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/upsample_bilateral_float1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc upsample_bilateral_float4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/upsample_bilateral_float4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc upsample_bilateral_unorm1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/upsample_bilateral_unorm1CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc upsample_bilateral_unorm4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/upsample_bilateral_unorm4CS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vDiscLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vDiscLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc lightVisualizerPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/lightVisualizerPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc volumetricLight_DirectionalPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/volumetricLight_DirectionalPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc volumetricLight_PointPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/volumetricLight_PointPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc volumetricLight_SpotPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/volumetricLight_SpotPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelClearOnlyNormalCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelClearOnlyNormalCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelGS.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelGS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelPS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelRadianceSecondaryBounceCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelRadianceSecondaryBounceCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelSceneCopyClearCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelSceneCopyClearCS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelSceneCopyClear_TemporalSmoothing.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelSceneCopyClear_TemporalSmoothing.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc voxelVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/voxelVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vPointLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vPointLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vRectangleLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vRectangleLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vSphereLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vSphereLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vSpotLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vSpotLightVS.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc objectPS_forward_water.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/objectPS_forward_water.cso  2>>../build_SPIRV_errors.log 
..\shadercompilers\dxc vTubeLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo shaders/spirv/vTubeLightVS.cso  2>>../build_SPIRV_errors.log 
cd .. 
