2>build_HLSL6_errors.log cls 
mkdir WickedEngine\shaders 
cd WickedEngine\shaders 
mkdir hlsl6
cd .. 
..\shadercompilers\dxc bloomcombineCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/bloomcombineCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc bloomseparateCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/bloomseparateCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc downsample4xCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/downsample4xCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_bilateral_float1CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_bilateral_float1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_bilateral_float3CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_bilateral_float3CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_bilateral_unorm4CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_bilateral_unorm4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_bilateral_wide_float1CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_bilateral_wide_float1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_bilateral_wide_float3CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_bilateral_wide_float3CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_bilateral_wide_float4CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_bilateral_wide_float4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_bilateral_wide_unorm1CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_bilateral_wide_unorm1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_bilateral_wide_unorm4CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_bilateral_wide_unorm4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_gaussian_float1CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_gaussian_float1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_gaussian_float3CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_gaussian_float3CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_gaussian_unorm1CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_gaussian_unorm1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_gaussian_unorm4CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_gaussian_unorm4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_gaussian_wide_float1CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_gaussian_wide_float1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_gaussian_wide_float3CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_gaussian_wide_float3CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_gaussian_wide_float4CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_gaussian_wide_float4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_gaussian_wide_unorm1CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_gaussian_wide_unorm1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_gaussian_wide_unorm4CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_gaussian_wide_unorm4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc captureImpostorPS_albedo.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/captureImpostorPS_albedo.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc captureImpostorPS_normal.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/captureImpostorPS_normal.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc captureImpostorPS_surface.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/captureImpostorPS_surface.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc chromatic_aberrationCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/chromatic_aberrationCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc circlePS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/circlePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc copytexture2D_float4CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/copytexture2D_float4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc copytexture2D_float4_borderexpandCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/copytexture2D_float4_borderexpandCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc copytexture2D_unorm4CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/copytexture2D_unorm4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc copytexture2D_unorm4_borderexpandCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/copytexture2D_unorm4_borderexpandCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cubeMapPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cubeMapPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cubeShadowVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cubeShadowVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cubeShadowVS_alphatest.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cubeShadowVS_alphatest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc cubeVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/cubeVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc decalPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/decalPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc decalVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/decalVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc deferredPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/deferredPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc depthoffield_mainCS_cheap.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/depthoffield_mainCS_cheap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc depthoffield_mainCS_earlyexit.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/depthoffield_mainCS_earlyexit.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc depthoffield_kickjobsCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/depthoffield_kickjobsCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc depthoffield_mainCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/depthoffield_mainCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc depthoffield_neighborhoodMaxCOCCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/depthoffield_neighborhoodMaxCOCCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc depthoffield_postfilterCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/depthoffield_postfilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc depthoffield_prepassCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/depthoffield_prepassCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc depthoffield_prepassCS_earlyexit.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/depthoffield_prepassCS_earlyexit.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc depthoffield_tileMaxCOC_horizontalCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/depthoffield_tileMaxCOC_horizontalCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc depthoffield_tileMaxCOC_verticalCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/depthoffield_tileMaxCOC_verticalCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc depthoffield_upsampleCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/depthoffield_upsampleCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc dirLightPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/dirLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc dirLightVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/dirLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc discLightPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/discLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc downsampleDepthBuffer4xPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/downsampleDepthBuffer4xPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticlePS_soft_distortion.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticlePS_soft_distortion.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticlePS_soft_lighting.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticlePS_soft_lighting.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_emitCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_emitCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_emitCS_FROMMESH.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_emitCS_FROMMESH.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_emitCS_volume.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_emitCS_volume.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_finishUpdateCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_finishUpdateCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_sphpartitionoffsetsCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_sphpartitionoffsetsCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_sphpartitionoffsetsresetCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_sphpartitionoffsetsresetCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMapPS_terrain.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMapPS_terrain.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc filterEnvMapCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/filterEnvMapCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain2D_float4_BicubicCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain2D_float4_BicubicCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain2D_unorm4_BicubicCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain2D_unorm4_BicubicCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain2D_unorm4_SimpleFilterCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain2D_unorm4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain3D_unorm4_SimpleFilterCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain3D_unorm4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChainCubeArray_float4_SimpleFilterCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChainCubeArray_float4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChainCubeArray_unorm4_SimpleFilterCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChainCubeArray_unorm4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChainCube_float4_SimpleFilterCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChainCube_float4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChainCube_unorm4_SimpleFilterCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChainCube_unorm4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc gpusortlib_kickoffSortCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/gpusortlib_kickoffSortCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_kickoffUpdateCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_kickoffUpdateCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_sphdensityCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_sphdensityCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_sphforceCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_sphforceCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_simulateCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS_DEPTHCOLLISIONS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_simulateCS_DEPTHCOLLISIONS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS_SORTING.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_simulateCS_SORTING.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_simulateCS_SORTING_DEPTHCOLLISIONS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_simulateCS_SORTING_DEPTHCOLLISIONS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc gpusortlib_sortCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/gpusortlib_sortCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc gpusortlib_sortInnerCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/gpusortlib_sortInnerCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc gpusortlib_sortStepCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/gpusortlib_sortStepCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticle_sphpartitionCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticle_sphpartitionCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc environmentalLightPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/environmentalLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMapPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMapPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMapVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMapVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMap_skyPS_dynamic.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMap_skyPS_dynamic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMap_skyPS_static.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMap_skyPS_static.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc envMap_skyVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/envMap_skyVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc fft_512x512_c2c_CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/fft_512x512_c2c_CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc fft_512x512_c2c_v2_CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/fft_512x512_c2c_v2_CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc fontPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/fontPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc fontVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/fontVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc forceFieldVisualizerPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/forceFieldVisualizerPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc forceFieldPlaneVisualizerVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/forceFieldPlaneVisualizerVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc forceFieldPointVisualizerVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/forceFieldPointVisualizerVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc fxaaCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/fxaaCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain2D_float4_SimpleFilterCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain2D_float4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc generateMIPChain3D_float4_SimpleFilterCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/generateMIPChain3D_float4_SimpleFilterCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticlePS_forward_transparent.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticlePS_forward_transparent.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticlePS_simplest.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticlePS_simplest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticlePS_tiledforward_transparent.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticlePS_tiledforward_transparent.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticle_simulateCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticle_simulateCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hbaoCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hbaoCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_backgroundblur.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_backgroundblur.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_backgroundblur_bicubic.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_backgroundblur_bicubic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_backgroundblur_masked.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_backgroundblur_masked.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_backgroundblur_masked_bicubic.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_backgroundblur_masked_bicubic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_bicubic.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_bicubic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_masked_bicubic.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_masked_bicubic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_separatenormalmap_bicubic.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_separatenormalmap_bicubic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorPS_alphatestonly.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorPS_alphatestonly.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorPS_deferred.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorPS_deferred.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorPS_forward.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorPS_forward.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorPS_simple.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorPS_simple.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorPS_tiledforward.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorPS_tiledforward.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorPS_wire.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorPS_wire.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc impostorVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/impostorVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc motionblurCS_cheap.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/motionblurCS_cheap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc motionblurCS_earlyexit.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/motionblurCS_earlyexit.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc motionblur_kickjobsCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/motionblur_kickjobsCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc motionblur_neighborhoodMaxVelocityCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/motionblur_neighborhoodMaxVelocityCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc motionblur_tileMaxVelocity_horizontalCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/motionblur_tileMaxVelocity_horizontalCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc motionblur_tileMaxVelocity_verticalCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/motionblur_tileMaxVelocity_verticalCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc msaoCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/msaoCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc msao_blurupsampleCS_blendout.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/msao_blurupsampleCS_blendout.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc msao_blurupsampleCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/msao_blurupsampleCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc msao_blurupsampleCS_premin_blendout.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/msao_blurupsampleCS_premin_blendout.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc msao_blurupsampleCS_premin.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/msao_blurupsampleCS_premin.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc msao_interleaveCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/msao_interleaveCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc msao_preparedepthbuffers1CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/msao_preparedepthbuffers1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc msao_preparedepthbuffers2CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/msao_preparedepthbuffers2CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred_normalmap_planarreflection.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred_normalmap_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred_planarreflection.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred_terrain.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred_terrain.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_terrain.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_terrain.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_hologram.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_hologram.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_paintradius.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_paintradius.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_terrain.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_terrain.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_voxelizer_terrain.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_voxelizer_terrain.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc oceanSurfacePS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/oceanSurfacePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc oceanSurfaceVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/oceanSurfaceVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticleVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticleVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_gaussian_float4CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_gaussian_float4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_separatenormalmap.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_separatenormalmap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imagePS_masked.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imagePS_masked.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc imageVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/imageVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lensFlareGS.hlsl -T gs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lensFlareGS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lensFlarePS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lensFlarePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lensFlareVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lensFlareVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_ADVANCED.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_ADVANCED.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_ADVANCED_DEBUG.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_ADVANCED_DEBUG.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_DEBUG.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_DEBUG.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_DEFERRED.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED_ADVANCED.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_DEFERRED_ADVANCED.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED_ADVANCED_DEBUG.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_DEFERRED_ADVANCED_DEBUG.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightCullingCS_DEFERRED_DEBUG.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightCullingCS_DEFERRED_DEBUG.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightShaftsCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightShaftsCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lineardepthCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lineardepthCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc paint_textureCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/paint_textureCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vertexcolorPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vertexcolorPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vertexcolorVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vertexcolorVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc luminancePass1CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/luminancePass1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc luminancePass2CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/luminancePass2CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc motionblurCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/motionblurCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectDS.hlsl -T ds_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectDS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectGS_voxelizer.hlsl -T gs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectGS_voxelizer.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectHS.hlsl -T hs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectHS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_alphatestonly.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_alphatestonly.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_debug.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_debug.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_blackout.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_blackout.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred_normalmap.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred_normalmap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred_normalmap_pom.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred_normalmap_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_deferred_pom.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_deferred_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_normalmap.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_normalmap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_normalmap_planarreflection.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_normalmap_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_normalmap_pom.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_normalmap_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_planarreflection.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_pom.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_transparent.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_normalmap_planarreflection.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_transparent_normalmap_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_normalmap_pom.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_transparent_normalmap_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_planarreflection.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_transparent_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_pom.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_transparent_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_simplest.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_simplest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_textureonly.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_textureonly.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_transparent_normalmap.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_transparent_normalmap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_normalmap.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_normalmap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_normalmap_planarreflection.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_normalmap_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_normalmap_pom.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_normalmap_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_planarreflection.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_pom.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_transparent.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_normalmap.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_transparent_normalmap.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_normalmap_planarreflection.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_transparent_normalmap_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_normalmap_pom.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_transparent_normalmap_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_planarreflection.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_transparent_planarreflection.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_transparent_pom.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_transparent_pom.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_tiledforward_water.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_tiledforward_water.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_voxelizer.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_voxelizer.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_common_tessellation.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_common_tessellation.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_common.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_common.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_debug.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_debug.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_positionstream.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_positionstream.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_simple.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_simple.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_simple_tessellation.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_simple_tessellation.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectVS_voxelizer.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectVS_voxelizer.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc oceanSimulatorCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/oceanSimulatorCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc oceanSurfaceSimplePS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/oceanSurfaceSimplePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc oceanUpdateDisplacementMapCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/oceanUpdateDisplacementMapCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc oceanUpdateGradientFoldingCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/oceanUpdateGradientFoldingCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc outlinePS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/outlinePS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc pointLightPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/pointLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc pointLightVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/pointLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticlePS_soft.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticlePS_soft.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticlePS_simplest.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticlePS_simplest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc emittedparticleVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/emittedparticleVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticlePS_alphatestonly.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticlePS_alphatestonly.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticlePS_deferred.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticlePS_deferred.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticlePS_forward.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticlePS_forward.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc hairparticlePS_tiledforward.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/hairparticlePS_tiledforward.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc bvh_propagateaabbCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/bvh_propagateaabbCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc bvh_hierarchyCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/bvh_hierarchyCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc bvh_primitivesCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/bvh_primitivesCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc raytrace_debugbvhPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/raytrace_debugbvhPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc raytrace_kickjobsCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/raytrace_kickjobsCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc raytrace_screenVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/raytrace_screenVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc raytrace_shadeCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/raytrace_shadeCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc raytrace_tilesortCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/raytrace_tilesortCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc rectangleLightPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/rectangleLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc renderlightmapPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/renderlightmapPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc renderlightmapVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/renderlightmapVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc resolveMSAADepthStencilCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/resolveMSAADepthStencilCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc screenPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/screenPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc screenPS_bicubic.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/screenPS_bicubic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc screenVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/screenVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc shadowPS_alphatest.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/shadowPS_alphatest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc shadowPS_transparent.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/shadowPS_transparent.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc shadowPS_water.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/shadowPS_water.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc shadowVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/shadowVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc shadowVS_alphatest.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/shadowVS_alphatest.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc shadowVS_transparent.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/shadowVS_transparent.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc sharpenCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/sharpenCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc skinningCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/skinningCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc skinningCS_LDS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/skinningCS_LDS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc skyPS_static.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/skyPS_static.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc skyPS_dynamic.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/skyPS_dynamic.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc skyVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/skyVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc sphereLightPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/sphereLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc sphereVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/sphereVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc spotLightPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/spotLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc spotLightVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/spotLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc ssaoCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/ssaoCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc ssr_medianCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/ssr_medianCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc ssr_raytraceCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/ssr_raytraceCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc sssPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/sssPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc ssr_resolveCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/ssr_resolveCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc ssr_temporalCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/ssr_temporalCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc sunPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/sunPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc temporalaaCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/temporalaaCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc tileFrustumsCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/tileFrustumsCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc tonemapCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/tonemapCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc raytrace_launchCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/raytrace_launchCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc raytrace_closesthitCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/raytrace_closesthitCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc trailPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/trailPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc trailVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/trailVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc tubeLightPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/tubeLightPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_bilateral_float4CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_bilateral_float4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc blur_bilateral_unorm1CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/blur_bilateral_unorm1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc upsample_bilateralPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/upsample_bilateralPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc upsample_bilateral_float1CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/upsample_bilateral_float1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc upsample_bilateral_float4CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/upsample_bilateral_float4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc upsample_bilateral_unorm1CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/upsample_bilateral_unorm1CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc upsample_bilateral_unorm4CS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/upsample_bilateral_unorm4CS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vDiscLightVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vDiscLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc lightVisualizerPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/lightVisualizerPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc volumetricLight_DirectionalPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/volumetricLight_DirectionalPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc volumetricLight_PointPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/volumetricLight_PointPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc volumetricLight_SpotPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/volumetricLight_SpotPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelClearOnlyNormalCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelClearOnlyNormalCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelGS.hlsl -T gs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelGS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelPS.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelPS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelRadianceSecondaryBounceCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelRadianceSecondaryBounceCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelSceneCopyClearCS.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelSceneCopyClearCS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelSceneCopyClear_TemporalSmoothing.hlsl -T cs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelSceneCopyClear_TemporalSmoothing.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc voxelVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/voxelVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vPointLightVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vPointLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vRectangleLightVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vRectangleLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vSphereLightVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vSphereLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vSpotLightVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vSpotLightVS.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc objectPS_forward_water.hlsl -T ps_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/objectPS_forward_water.cso  2>>../build_HLSL6_errors.log 
..\shadercompilers\dxc vTubeLightVS.hlsl -T vs_6_1  -D SHADER_MODEL_6  -flegacy-macro-expansion -Fo shaders/hlsl6/vTubeLightVS.cso  2>>../build_HLSL6_errors.log 
cd .. 
